# Generated by Django 6.0.1 on 2026-02-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_oder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oder',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
    ]
