# Generated by Django 6.0.1 on 2026-02-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pnone',
            new_name='phone',
        ),
    ]
